name:                concurrent-models
version:             0.2.0.0
github:              "vojiranto/concurrent-models"
license:             BSD3
author:              "Dmitrij Aleksandrovicx Pavluk"
maintainer:          "dmitrij.pavluk.hs@gmail.com"
copyright:           "2018 Dmitrij Aleksandrovicx Pavluk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vojiranto/concurrent-models#readme>

default-extensions:
- NoImplicitPrelude
- TypeSynonymInstances
- FlexibleInstances
- MultiParamTypeClasses
- OverloadedStrings
- ScopedTypeVariables
- LambdaCase
- GADTs

dependencies:
- base >= 4.7 && < 5
- universum
- template-haskell
- th-abstraction
- network
- free
- clock
- extra
- text
- containers
- lens
- stm
- unique
- hashable
- bytestring
- base58string
- binary
- aeson

executables:
  example:
    main:                Main.hs
    source-dirs:
    - examples
    - app

    dependencies:
    - concurrent-models

library:
  source-dirs: src
  exposed-modules:
    - Control.Concurrent.Model
    - Control.Concurrent.Model.Core
    - Control.Concurrent.Model.Core.Data
    - Control.Concurrent.Model.Core.Data.Describe
    - Control.Concurrent.Model.Core.Data.Event
    - Control.Concurrent.Model.Core.Data.TextId
    - Control.Concurrent.Model.Core.Interface
    - Control.Concurrent.Model.Core.Interface.Listener
    - Control.Concurrent.Model.Core.Interface.Loger
    - Control.Concurrent.Model.Core.Interface.Math
    - Control.Concurrent.Model.Core.Interface.This
    - Control.Concurrent.Model.StateMachine
    - Control.Concurrent.Model.Actor
    - Control.Concurrent.Service.Subscription
    - Control.Concurrent.Service.StreamManager
    - Control.Concurrent.Service.Serialization.Common
    - Control.Concurrent.Service.Serialization.Binary
    - Control.Concurrent.Service.Stream
    - Control.Concurrent.Node.Network.Tcp
    - Control.Concurrent.Node.Console 
    - Control.Concurrent.Node.Metronome
    - Control.Concurrent.Node.Loger
    - Control.Concurrent.Flag
  ghc-options:
  - -Wall
  - -Werror

tests:
  Actor-test:
    main:                Spec.hs
    source-dirs:
    - test
    - examples

    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concurrent-models
    - async
    - nanospec