name:                concurrent-models
version:             0.1.0.0
github:              "vojiranto/concurrent-models"
license:             BSD3
author:              "Dmitrij Aleksandrovicx Pavluk"
maintainer:          "dmitrij.pavluk.hs@gmail.com"
copyright:           "2018 Dmitrij Aleksandrovicx Pavluk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vojiranto/concurrent-models#readme>

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- LambdaCase
- GADTs

dependencies:
- base >= 4.7 && < 5
- universum
- template-haskell
- th-abstraction
- free
- text
- containers
- lens
- stm
- unique
- hashable
- base58string

executables:
  example:
    main:                Main.hs
    source-dirs:
    - examples
    - app

    dependencies:
    - concurrent-models

library:
  source-dirs: src
  exposed-modules:
    - Control.StateMachine
    - Control.Actor
    - Control.Loger
    - Data.Flag
  ghc-options:
  - -Wall
  - -Werror

tests:
  Actor-test:
    main:                Spec.hs
    source-dirs:
    - test
    - examples

    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concurrent-models
    - async
    - nanospec